### ISSUE TITLE
一个小问题，跪求解答

### ISSUE THREAD

**Issue by dongdongyee** [VectXmy/FCOS.Pytorch#20]
感谢您分享的代码！有些小问题向您请教，提前致谢！

https://github.com/VectXmy/FCOS.Pytorch/blob/79caa8db20bc39fddfec096b26fbe54a7ff6ff99/model/fcos.py#L88
1. 请问在fcos.py 的line 88 处，为何要对classes做+1的处理？
2. 请问在inference阶段，为什么没有过滤掉预测为background类别的score和reg？

**Comment by VectXmy** [comment]
1. 我们使用的是二分类交叉熵损失，我们使用max函数得到最大的类别的index，这个index是从0开始的，我们定义的CLASS_NAMES的index0对应背景类别，所以我们将classes加1。
2. 同1，例如coco数据集80个类别，我们head的cls分支输出通道就是80，没有背景类别的通道，我们使用的是二分类交叉熵损失。

**Comment by dongdongyee** [comment]
十分感谢您！
