### ISSUE TITLE
about weights and eval

### ISSUE THREAD

**Issue by zhenghao977** [VectXmy/FCOS.Pytorch#7]
您好感谢提供的代码！
用您转换好的权重来测试coco2017minval数据，但是AP看起来不知道哪里出了问题，我已经把对应的score阈值改为0.005，结果如下：
all classes AP=====>
 {1: 9.279020135473695e-05, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.0, 9: 0.0, 10: 0.0, 11: 0.0, 12: 0.02666666666666667, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.0, 17: 0.0, 18: 0.0, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.0, 23: 0.0, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.0, 31: 0.0, 32: 0.0, 33: 0.0, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.0, 38: 0.0, 39: 0.0, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.0, 46: 0.0, 47: 0.0, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.0, 55: 0.0, 56: 0.0, 57: 0.0, 58: 0.0, 59: 0.0, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.0, 65: 0.0, 66: 0.0, 67: 0.0, 68: 0.0, 69: 0.0, 70: 0.0, 71: 0.0, 72: 0.0, 73: 0.0, 74: 0.0, 75: 0.003745318352059925, 76: 0.0, 77: 0.0, 78: 0.0, 79: 0.0, 80: 0.0, 81: 0.0}
mAP=====>0.000
而且似乎用这个权重预测得到的score都不是特别高，结果如：
tensor([[0.2651, 0.2518, 0.2494, 0.2301, 0.2068, 0.2050, 0.2021, 0.1942, 0.1792,
         0.1790, 0.1769, 0.1678, 0.1639, 0.1632, 0.1614, 0.1611, 0.1585, 0.1556,
         0.1549, 0.1547, 0.1539, 0.1535, 0.1516, 0.1501, 0.1490, 0.1474, 0.1456,
         0.1423]], grad_fn=<StackBackward>)
希望得到您的帮助！

**Comment by VectXmy** [comment]
I have explained in Readme.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chenney0813"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 晚上6:02
收件人:&nbsp;"VectXmy/FCOS.Pytorch"<FCOS.Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[VectXmy/FCOS.Pytorch] about weights and eval (#7)





 
您好感谢提供的代码！
 用您转换好的权重来测试coco2017minval数据，但是AP看起来不知道哪里出了问题，我已经把对应的score阈值改为0.005，结果如下：
 all classes AP=====&gt;
 {1: 9.279020135473695e-05, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.0, 9: 0.0, 10: 0.0, 11: 0.0, 12: 0.02666666666666667, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.0, 17: 0.0, 18: 0.0, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.0, 23: 0.0, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.0, 31: 0.0, 32: 0.0, 33: 0.0, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.0, 38: 0.0, 39: 0.0, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.0, 46: 0.0, 47: 0.0, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.0, 55: 0.0, 56: 0.0, 57: 0.0, 58: 0.0, 59: 0.0, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.0, 65: 0.0, 66: 0.0, 67: 0.0, 68: 0.0, 69: 0.0, 70: 0.0, 71: 0.0, 72: 0.0, 73: 0.0, 74: 0.0, 75: 0.003745318352059925, 76: 0.0, 77: 0.0, 78: 0.0, 79: 0.0, 80: 0.0, 81: 0.0}
 mAP=====&gt;0.000
 而且似乎用这个权重预测得到的score都不是特别高，结果如：
 tensor([[0.2651, 0.2518, 0.2494, 0.2301, 0.2068, 0.2050, 0.2021, 0.1942, 0.1792,
 0.1790, 0.1769, 0.1678, 0.1639, 0.1632, 0.1614, 0.1611, 0.1585, 0.1556,
 0.1549, 0.1547, 0.1539, 0.1535, 0.1516, 0.1501, 0.1490, 0.1474, 0.1456,
 0.1423]], grad_fn=)
 希望得到您的帮助！

**Comment by VectXmy** [comment]
You need to modify the preprocessing， you can refer to demo.py.

**Comment by zhenghao977** [comment]
ok , I will try! thank you very much !
